import Providers from "./Providers";

export const metadata = {
  title: "Erwan MARIE | Portfolio - Front-End Developer",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
